# Whether to allow connections across worlds (i.e. between Nether and Overworld)
allow-cross-world-connections: false

# Maximum distance between source and target chests (0 = unlimited)
max-distance: 100