# Whether to allow connections across worlds (i.e. between Nether and Overworld)
allow-cross-world-connections: false

# Maximum distance between source and target chests (0 = unlimited)
max-distance: 100

# Maximum number of different names per player (0 = unlimited)
max-names-per-player: 0

# Maximum number of signs per name (0 = unlimited)
max-signs-per-name: 0

# Whether to allow multiple connected chests per sign (i.e. a 4 x 4 field of barrels where only one of them has a sign)
allow-multi-chests: true

# The maximum number of chest blocks used for the multi chest feature (0 = unlimited)
max-multi-chests-blocks: 0

# Whether to allow persistent items (i.e. items can be added and removed from the list of persistent items to allow using hoppers as targets)
allow-persistent-chests: true

# Interval (in ticks) at which items are checked and transferred
transfer-interval: 10
