name: ${project.name}
version: ${project.version}
description: '${project.description}'
author: Programie
website: ${project.url}
api-version: 1.14
main: com.selfcoders.itemsorter.ItemSorter
permissions:
  itemsorter.*:
    children:
      - itemsorter.create
  itemsorter.create:
    description: 'Allow to create ItemSorter signs'
    default: true