name: ${project.name}
version: ${project.version}
description: '${project.description}'
author: Programie
website: ${project.url}
api-version: 1.20
main: com.selfcoders.itemsorter.ItemSorter
commands:
  itemsorter:
    description: 'Command for various ItemSorter actions'
    permission: itemsorter.command
    usage: 'Execute /itemsorter to list available actions'
permissions:
  itemsorter.*:
    children:
      - itemsorter.create
      - itemsorter.destroyAny
    default: op
  itemsorter.create:
    description: 'Allow to create and destroy your own ItemSorter signs'
    default: true
  itemsorter.destroyAny:
    description: 'Allow to destroy any ItemSorter signs (not just your own)'
    default: op
  itemsorter.command:
    description: 'Allow to execute the /itemsorter command'
    default: op
